version: "3"
services:
  mynote-client:
    image: mynote-client
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mynote-app
  mynote-server:
    image: mynote-server
    ports:
      - "3001:3001"
    networks:
      - mynote-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mynote-app
    volumes:
      - mongo-data:/data/db
networks:
  mynote-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local